#!/bin/bash
set -e

[ "$(id -u)" -eq 0 ] || { echo "ERROR: uninstall.sh must be run as root (use sudo)"; exit 1; }

echo "[uninstall] streamdeck-ctrl uninstaller"

# Stop and disable service
echo "[1/4] Stopping and disabling service..."
systemctl stop streamdeck-ctrl 2>/dev/null || true
systemctl disable streamdeck-ctrl 2>/dev/null || true

# Remove systemd unit (generated by setup.sh)
echo "[2/4] Removing systemd unit..."
rm -f /etc/systemd/system/streamdeck-ctrl.service
systemctl daemon-reload

# Remove udev rule
echo "[3/4] Removing udev rule..."
rm -f /etc/udev/rules.d/99-streamdeck.rules
udevadm control --reload-rules 2>/dev/null || true

# Remove tmpfiles.d and runtime dir
echo "[4/4] Removing tmpfiles.d entry..."
rm -f /etc/tmpfiles.d/streamdeck-ctrl.conf
rm -rf /run/streamdeck-ctrl

echo ""
echo "[uninstall] Uninstallation complete."
echo "[uninstall] The repo directory was NOT removed."
echo "[uninstall] Note: {INSTALL_DIR} replacements in config files are NOT reverted."
echo "[uninstall]       Use 'git checkout -- <file>' to restore original placeholders."
